services:
  rabbitmq:
    build:
      dockerfile: rabbitmq.Dockerfile
      args:
        - RMQ_PORT=${RMQ_PORT}
        - RMQ_GID=${RMQ_GID}
        - RMQ_UID=${RMQ_UID}
        - RMQ_LINUX_USER=${RMQ_LINUX_USER}
        - RMQ_LINUX_GROUP=${RMQ_LINUX_GROUP}
    env_file:
      - ./.env
    restart: always
    container_name: 'rabbitmq-socketio'
    ports:
        - ${RMQ_PORT}:5672
    networks:
      - whats-organizer_back

networks:
  whats-organizer_back: