services:
  backend-0:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: wo-backend-0
    restart: unless-stopped
    env_file: .env.backend
    environment:
      - FLASK_PORT=3000
    command: >
      gunicorn --preload -w 2 --threads 4
      -b 0.0.0.0:3000 app:app
      --timeout 1000 --limit-request-line 0
    volumes:
      - backend-0-data:/app/zip_tests
    networks:
      - backend-net

  backend-1:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: wo-backend-1
    restart: unless-stopped
    env_file: .env.backend
    environment:
      - FLASK_PORT=3001
    command: >
      gunicorn --preload -w 2 --threads 4
      -b 0.0.0.0:3001 app:app
      --timeout 1000 --limit-request-line 0
    volumes:
      - backend-1-data:/app/zip_tests
    networks:
      - backend-net

  nginx:
    image: nginx:alpine
    container_name: wo-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./infra/docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-0
      - backend-1
    networks:
      - backend-net

volumes:
  backend-0-data:
  backend-1-data:

networks:
  backend-net:
    driver: bridge
