name: Run CI/CD Zero Config Deploy Pipeline
on:
  push:
    branches:
      - master
  workflow_call:
    secrets:
      host:
        required: true
      username:
        required: true
      key:
        required: true
      port:
        required: true
      fingerprint:
        required: true
      SHARED_BACK_FRONT_ENV:
        required: true
      SHARED_BACK_NGINX_ENV:
        required: true
      SHARED_BACK_RABBITMQ_ENV:
        required: true
      SHARED_BACK_FRONT_NGINX_ENV:
        required: true
      BACK_ENV:
        required: true
      FRONT_ENV:
        required: true
      NGINX_ENV:
        required: true

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    secrets:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        fingerprint: ${{ secrets.FINGERPRINT }}
        SHARED_BACK_FRONT_ENV: ${{ secrets.SHARED_BACK_FRONT_ENV }}
        SHARED_BACK_NGINX_ENV: ${{ secrets.SHARED_BACK_NGINX_ENV }}
        SHARED_BACK_RABBITMQ_ENV: ${{ secrets.SHARED_BACK_RABBITMQ_ENV }}
        SHARED_BACK_FRONT_NGINX_ENV: ${{ secrets.SHARED_BACK_FRONT_NGINX_ENV }}
        BACK_ENV: ${{ secrets.BACK_ENV }}
        FRONT_ENV: ${{ secrets.FRONT_ENV }}
        NGINX_ENV: ${{ secrets.NGINX_ENV }}
        envs: "SHARED_BACK_FRONT_ENV,SHARED_BACK_NGINX_ENV,SHARED_BACK_RABBITMQ_ENV,SHARED_BACK_FRONT_NGINX_ENV,BACK_ENV,FRONT_ENV,NGINX_ENV"

  back-deploy:
    needs: [setup]
    uses: ./.github/workflows/back.yml
    secrets:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        fingerprint: ${{ secrets.FINGERPRINT }}

  front-deploy:
    needs: [setup]
    uses: ./.github/workflows/front.yml
    secrets:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        fingerprint: ${{ secrets.FINGERPRINT }}

  nginx-deploy:
    needs: [setup, back-deploy, front-deploy]
    uses: ./.github/workflows/nginx.yml
    secrets:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        fingerprint: ${{ secrets.FINGERPRINT }}

  rabbitmq-deploy:
    needs: [setup, back-deploy]
    uses: ./.github/workflows/rabbitmq.yml
    secrets:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        fingerprint: ${{ secrets.FINGERPRINT }}