name: Back deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing Back deployment using key
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        fingerprint: ${{ secrets.FINGERPRINT }}
        script: |
          set -u
          export PROJECT="back"
          export PROJECT_INFRA="infra"
          export BRANCH="master"
          export USER="${PROJECT}"
          export GROUP="${USER}"
          export HOME="/home/${USER}"
          export PROJECT_DIR="${HOME}/whats-organizer"
          export INFRA_DIR="${PROJECT_DIR}/${PROJECT_INFRA}"
          export ENV_DIR="${HOME}"
          export SERVICE="back@.service"
          export ERROR=false
          export DISK_USAGE=$(df -h / | grep -E -o "[0-9]+%" | cut -d "%" -f 1)
          export MESSAGE="Whats-Organizer-${PROJECT}:"
          export GIT_URL="https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          export ENOENT=127
          readonly PROJECT PROJECT_INFRA BRANCH USER GROUP HOME PROJECT_DIR INFRA_DIR ENV_DIR SERVICE DISK_USAGE GIT_URL ENOENT

          if ! getent group "${GROUP}" >/dev/null; then
            groupadd -r "${GROUP}"
          fi

          if ! id -u "${USER}" >/dev/null 2>&1; then
            useradd -m -d "${HOME}" -g "${GROUP}" -s /bin/bash "${USER}"
          fi

          if command -v pacman >/dev/null 2>&1; then
            pacman --noconfirm  -Ss
            pacman --noconfirm  -Syu
            if ! command -v git >/dev/null 2>&1; then
                pacman --noconfirm -S git
            fi
            if ! command -v curl >/dev/null 2>&1; then
                pacman --noconfirm -S curl
            fi
            if ! command -v rabbitmq >/dev/null 2>&1; then
                pacman --noconfirm -S rabbitmq
            fi
            if ! command -v getent >/dev/null 2>&1; then
                pacman --noconfirm -S getent
            fi
          fi

          sudo -u "${USER}" bash <<EOF
          if [ ! -d "${PROJECT_DIR}/.git" ]; then
            [ -d "${PROJECT_DIR}" ] && rm -rf "${PROJECT_DIR}"
            mkdir -p "${PROJECT_DIR}"
            cd "${PROJECT_DIR}"
            git clone --filter=blob:none --sparse "${GIT_URL}" .
            git sparse-checkout set "${PROJECT}" "${PROJECT_INFRA}"
          else
            cd "${PROJECT_DIR}"
            git remote set-url origin "${GIT_URL}"
            git fetch origin "${BRANCH}"
            git diff --quiet HEAD "origin/${BRANCH}" -- "${PROJECT}"
            PROJECT_CHANGED=\$?
            git diff --quiet HEAD "origin/${BRANCH}" -- "${PROJECT_INFRA}"
            INFRA_CHANGED=\$?
            if [ \${PROJECT_CHANGED} -eq 0 ] && [ \${INFRA_CHANGED} -eq 0 ]; then
              echo "Nenhuma mudança detectada na pasta ${PROJECT}"
              exit 1
            fi
            git reset --hard "origin/${BRANCH}"
            git sparse-checkout set "${PROJECT}" "${PROJECT_INFRA}"
          fi
          EOF

          readonly PROJECT_CHANGED=$?
          if [ ${PROJECT_CHANGED} -eq 1 ]; then
            exit
          fi

          mkdir -p zip_tests && chown "${USER}:${GROUP}" zip_tests

          sudo -u "${USER}" bash <<EOF
          cd "${PROJECT_DIR}/${PROJECT}"
          if [ -f "${ENV_DIR}/.env" ]; then
            cp "${ENV_DIR}/.env" .
          else
            echo "Erro: Falta o arquivo de segredos .env em ${ENV_DIR}/.env"
            exit ${ENOENT}
          fi

          if [ ! -d .venv ]; then
            python3 -m venv .venv
          fi
          source .venv/bin/activate
          pip3 install -r requirements.txt
          pip3 install playwright==1.49.1
          python3 -m compileall .
          EOF

          readonly STATUS=$?
          if [ ${STATUS} -ne 0 ]; then
            if [ ${STATUS} -eq ${ENOENT} ]; then
              exit ${STATUS}
            fi
            # else
            export ERROR=true
          fi

          sysctl -w net.ipv6.conf.all.disable_ipv6=1 net.ipv6.conf.default.disable_ipv6=1 net.ipv6.conf.lo.disable_ipv6=1

          cp "${INFRA_DIR}/${SERVICE}" "/etc/systemd/system/${SERVICE}" ||
            export ERROR=true
          systemctl daemon-reload || export ERROR=true

          set -a
          source "${ENV_DIR}/.env" || export ERROR=true
          set +a
  
          systemctl restart $(seq ${FLASK_PORT_START} ${FLASK_PORT_END} | xargs -I{} systemd-escape --template="${SERVICE}" {}) ||
            export ERROR=true
          systemctl enable $(seq ${FLASK_PORT_START} ${FLASK_PORT_END} | xargs -I{} systemd-escape --template="${SERVICE}" {}) ||
            export ERROR=true

          if [ ${ERROR} = true ]; then
            export MESSAGE="${MESSAGE} Falhou ao Subir Imagem de Docker!"
          else
            export MESSAGE="${MESSAGE} Build feita com sucesso!"
          fi
          [ "$DISK_USAGE" -lt 90 ] || \
            export MESSAGE="${MESSAGE} *** AVISO: Disco Lotado ***"
          curl -X POST "https://hooks.zapier.com/hooks/catch/1863715/215sl1w/" \
               -H "Content-Type: application/json" \
               -d "{ \"message\": \"${MESSAGE}\" }"


