name: remote ssh command
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          export PROJECT=back
          export PROJECT_DIR="/root/whats-organizer-${PROJECT}"
          export ENV_DIR=/root/envs/${PROJECT}
          export ERROR=false
          export DISK_USAGE=$(df -h / | egrep -o "[0-9]+%" | cut -d "%" -f 1)
          export MESSAGE="Whats-Organizer-${PROJECT}:"
          if [ ! -d ${PROJECT_DIR} ]; then
            mkdir ${PROJECT_DIR}
            cd ${PROJECT_DIR}
            git clone https://github.com/${{ github.repository }} ${PROJECT_DIR}
          else
            cd ${PROJECT_DIR}
            git reset --hard origin
            git pull
          fi
          cp ${ENV_DIR}/.env .
          cp ${ENV_DIR}/nginx.env ./infra/server/.env
          docker compose -f docker-compose.yml -f docker-compose.prod.yml build || \
            export ERROR=true
          docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d || \
            export ERROR=true
          docker image prune --force
          docker container prune --force
          if [ ${ERROR} = true ]; then
            export MESSAGE="${MESSAGE} Falhou ao Subir Imagem de Docker!"
          else
            export MESSAGE="${MESSAGE} Build feita com sucesso!"
          fi
          [ "$DISK_USAGE" -lt 90 ] || \
            export MESSAGE="${MESSAGE} *** AVISO: Disco Lotado ***"
          curl -X POST "https://hooks.zapier.com/hooks/catch/1863715/215sl1w/" \
               -H "Content-Type: application/json" \
               -d "{ \"message\": \"${MESSAGE}\" }"


