name: remote ssh command
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          if [ -d /root/whats-organizer-back ]; then
            rm -r /root/whats-organizer-back
          fi
          mkdir /root/whats-organizer-back
          cd /root/whats-organizer-back
          git clone https://github.com/${{ github.repository }} ./
          cp /root/envs/back/.env .
          cp /root/envs/back/nginx.env ./infra/server/.env
          docker compose build
          docker compose up -d
          docker image prune --force
          docker container prune --force
